### ISSUE TITLE
CI/CD not working on merge

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/awesome-notebooks#1345]
Error while merging new template on repository => https://github.com/jupyter-naas/awesome-notebooks/actions/runs/3872409080/jobs/6601658903

![image](https://user-images.githubusercontent.com/48032461/211303687-5f2d74a1-58f0-4990-980c-9f025e60e6a9.png)

**Comment by FlorentLvr** [comment]
@srini047, can you have a look on this error?
The GitHub action failed everytime we merged:


![Image](https://user-images.githubusercontent.com/48032461/218993748-54f3fe02-10f4-450a-a1c8-3984ad6b4e70.png)


Let me know if you need more information.

**Comment by srini047** [comment]
I have made the following changes:
https://github.com/jupyter-naas/awesome-notebooks/blob/issue-1345/.github/workflows/generate_readme.yaml

```
name: Generate Readme
on:
  push:
    branches:
      - master
jobs:
  generate-readme:
    if: "!startsWith(github.event.head_commit.message, 'generateReadme:')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
    - run: "pip install MarkupSafe==2.0.1"
    - run: "pip install numpy==1.21.0"
    - run: "pip install notebook"
    - run: "pip install naas_drivers[markdown]"
    - run: "pip install papermill"
    - run: "pip install Markdown==3.3.7"
    - run: "jupyter nbconvert --execute generate_readme.ipynb --inplace"
    - run: "jupyter nbconvert --clear-output --inplace generate_readme.ipynb"
    - uses: EndBug/add-and-commit@v7.2.1
      with:
        message: 'generateReadme: Refresh'
```

Reasons to make the change:
- By default takes the Python version `3.10` but `numpy` has errors in building wheels. So used python version `3.9`
- Installed a specific version of Numpy i.e. `1.19.5` as per this [PR](https://github.com/cvxgrp/pymde/pull/41).

I think this would resolve the matter. But I would like to know how to test the CI/CD pipelines locally or any other platform as I'm new to it. Any help on this is appreciated.
